name: Monthly Webhostmost Login

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests

      - name: Install Chromium dependencies
        run: playwright install --with-deps chromium

      - name: Perform Webhostmost login
        env:
          WEBHOSTMOST_EMAIL: ${{ secrets.WEBHOSTMOST_EMAIL }}
          WEBHOSTMOST_PASSWORD: ${{ secrets.WEBHOSTMOST_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          set +e
          python scripts/webhostmost_login.py
          status=$?
          if [ "$status" -eq 3 ]; then
            echo "Transient issue detected, retrying once..."
            python scripts/webhostmost_login.py
            status=$?
          fi
          exit "$status"
